services:
  school-web:
    image: ${IMAGE_NAME:-schola-school-web:latest}
    container_name: ${DOCKER_NAME:-school-web}
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
