/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as ListRouteImport } from './routes/list'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthenticatedOnboardingRouteRouteImport } from './routes/_authenticated/onboarding/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedOnboardingProfileRouteImport } from './routes/_authenticated/onboarding/profile'
import { Route as AuthenticatedOnboardingBranchRouteImport } from './routes/_authenticated/onboarding/branch'
import { Route as AuthenticatedOnboardingAcademicRouteImport } from './routes/_authenticated/onboarding/academic'
import { Route as AuthenticatedDashboardTimetableRouteImport } from './routes/_authenticated/dashboard/timetable'
import { Route as AuthenticatedDashboardSubjectsRouteImport } from './routes/_authenticated/dashboard/subjects'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardSessionsRouteImport } from './routes/_authenticated/dashboard/sessions'
import { Route as AuthenticatedDashboardResultsRouteImport } from './routes/_authenticated/dashboard/results'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard/reports'
import { Route as AuthenticatedDashboardExamsRouteImport } from './routes/_authenticated/dashboard/exams'
import { Route as AuthenticatedDashboardDepartmentsRouteImport } from './routes/_authenticated/dashboard/departments'
import { Route as AuthenticatedDashboardClassesRouteImport } from './routes/_authenticated/dashboard/classes'
import { Route as AuthenticatedDashboardBranchesRouteImport } from './routes/_authenticated/dashboard/branches'
import { Route as AuthenticatedDashboardAssignmentsRouteImport } from './routes/_authenticated/dashboard/assignments'
import { Route as AuthenticatedDashboardAnnouncementsRouteImport } from './routes/_authenticated/dashboard/announcements'
import { Route as AuthenticatedDashboardStudentsIndexRouteImport } from './routes/_authenticated/dashboard/students.index'
import { Route as AuthenticatedDashboardStaffIndexRouteImport } from './routes/_authenticated/dashboard/staff.index'
import { Route as AuthenticatedDashboardLessonNotesIndexRouteImport } from './routes/_authenticated/dashboard/lesson-notes.index'
import { Route as AuthenticatedDashboardStudentsNewRouteImport } from './routes/_authenticated/dashboard/students.new'
import { Route as AuthenticatedDashboardStaffNewRouteImport } from './routes/_authenticated/dashboard/staff.new'
import { Route as AuthenticatedDashboardHrPayrollRouteImport } from './routes/_authenticated/dashboard/hr.payroll'
import { Route as AuthenticatedDashboardHrLeavesRouteImport } from './routes/_authenticated/dashboard/hr.leaves'
import { Route as AuthenticatedDashboardAttendanceStudentsRouteImport } from './routes/_authenticated/dashboard/attendance/students'
import { Route as AuthenticatedDashboardAttendanceStaffRouteImport } from './routes/_authenticated/dashboard/attendance/staff'
import { Route as AuthenticatedDashboardStudentsStudentIdIndexRouteImport } from './routes/_authenticated/dashboard/students/$studentId.index'
import { Route as AuthenticatedDashboardStaffStaffIdIndexRouteImport } from './routes/_authenticated/dashboard/staff/$staffId.index'
import { Route as AuthenticatedDashboardLessonNotesIdIndexRouteImport } from './routes/_authenticated/dashboard/lesson-notes.$id.index'
import { Route as AuthenticatedDashboardStudentsStudentIdEditRouteImport } from './routes/_authenticated/dashboard/students/$studentId.edit'
import { Route as AuthenticatedDashboardStaffStaffIdEditRouteImport } from './routes/_authenticated/dashboard/staff/$staffId.edit'
import { Route as AuthenticatedDashboardLessonNotesIdEditRouteImport } from './routes/_authenticated/dashboard/lesson-notes.$id.edit'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedOnboardingRouteRoute =
  AuthenticatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedOnboardingProfileRoute =
  AuthenticatedOnboardingProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingBranchRoute =
  AuthenticatedOnboardingBranchRouteImport.update({
    id: '/branch',
    path: '/branch',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingAcademicRoute =
  AuthenticatedOnboardingAcademicRouteImport.update({
    id: '/academic',
    path: '/academic',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedDashboardTimetableRoute =
  AuthenticatedDashboardTimetableRouteImport.update({
    id: '/timetable',
    path: '/timetable',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSubjectsRoute =
  AuthenticatedDashboardSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSessionsRoute =
  AuthenticatedDashboardSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardResultsRoute =
  AuthenticatedDashboardResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardExamsRoute =
  AuthenticatedDashboardExamsRouteImport.update({
    id: '/exams',
    path: '/exams',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardDepartmentsRoute =
  AuthenticatedDashboardDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardClassesRoute =
  AuthenticatedDashboardClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardBranchesRoute =
  AuthenticatedDashboardBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAssignmentsRoute =
  AuthenticatedDashboardAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAnnouncementsRoute =
  AuthenticatedDashboardAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStudentsIndexRoute =
  AuthenticatedDashboardStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStaffIndexRoute =
  AuthenticatedDashboardStaffIndexRouteImport.update({
    id: '/staff/',
    path: '/staff/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardLessonNotesIndexRoute =
  AuthenticatedDashboardLessonNotesIndexRouteImport.update({
    id: '/lesson-notes/',
    path: '/lesson-notes/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStudentsNewRoute =
  AuthenticatedDashboardStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStaffNewRoute =
  AuthenticatedDashboardStaffNewRouteImport.update({
    id: '/staff/new',
    path: '/staff/new',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardHrPayrollRoute =
  AuthenticatedDashboardHrPayrollRouteImport.update({
    id: '/hr/payroll',
    path: '/hr/payroll',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardHrLeavesRoute =
  AuthenticatedDashboardHrLeavesRouteImport.update({
    id: '/hr/leaves',
    path: '/hr/leaves',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAttendanceStudentsRoute =
  AuthenticatedDashboardAttendanceStudentsRouteImport.update({
    id: '/attendance/students',
    path: '/attendance/students',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAttendanceStaffRoute =
  AuthenticatedDashboardAttendanceStaffRouteImport.update({
    id: '/attendance/staff',
    path: '/attendance/staff',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStudentsStudentIdIndexRoute =
  AuthenticatedDashboardStudentsStudentIdIndexRouteImport.update({
    id: '/students/$studentId/',
    path: '/students/$studentId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStaffStaffIdIndexRoute =
  AuthenticatedDashboardStaffStaffIdIndexRouteImport.update({
    id: '/staff/$staffId/',
    path: '/staff/$staffId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardLessonNotesIdIndexRoute =
  AuthenticatedDashboardLessonNotesIdIndexRouteImport.update({
    id: '/lesson-notes/$id/',
    path: '/lesson-notes/$id/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStudentsStudentIdEditRoute =
  AuthenticatedDashboardStudentsStudentIdEditRouteImport.update({
    id: '/students/$studentId/edit',
    path: '/students/$studentId/edit',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStaffStaffIdEditRoute =
  AuthenticatedDashboardStaffStaffIdEditRouteImport.update({
    id: '/staff/$staffId/edit',
    path: '/staff/$staffId/edit',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardLessonNotesIdEditRoute =
  AuthenticatedDashboardLessonNotesIdEditRouteImport.update({
    id: '/lesson-notes/$id/edit',
    path: '/lesson-notes/$id/edit',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/redirect': typeof RedirectRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/announcements': typeof AuthenticatedDashboardAnnouncementsRoute
  '/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/dashboard/departments': typeof AuthenticatedDashboardDepartmentsRoute
  '/dashboard/exams': typeof AuthenticatedDashboardExamsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/results': typeof AuthenticatedDashboardResultsRoute
  '/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/subjects': typeof AuthenticatedDashboardSubjectsRoute
  '/dashboard/timetable': typeof AuthenticatedDashboardTimetableRoute
  '/onboarding/academic': typeof AuthenticatedOnboardingAcademicRoute
  '/onboarding/branch': typeof AuthenticatedOnboardingBranchRoute
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/attendance/staff': typeof AuthenticatedDashboardAttendanceStaffRoute
  '/dashboard/attendance/students': typeof AuthenticatedDashboardAttendanceStudentsRoute
  '/dashboard/hr/leaves': typeof AuthenticatedDashboardHrLeavesRoute
  '/dashboard/hr/payroll': typeof AuthenticatedDashboardHrPayrollRoute
  '/dashboard/staff/new': typeof AuthenticatedDashboardStaffNewRoute
  '/dashboard/students/new': typeof AuthenticatedDashboardStudentsNewRoute
  '/dashboard/lesson-notes/': typeof AuthenticatedDashboardLessonNotesIndexRoute
  '/dashboard/staff/': typeof AuthenticatedDashboardStaffIndexRoute
  '/dashboard/students/': typeof AuthenticatedDashboardStudentsIndexRoute
  '/dashboard/lesson-notes/$id/edit': typeof AuthenticatedDashboardLessonNotesIdEditRoute
  '/dashboard/staff/$staffId/edit': typeof AuthenticatedDashboardStaffStaffIdEditRoute
  '/dashboard/students/$studentId/edit': typeof AuthenticatedDashboardStudentsStudentIdEditRoute
  '/dashboard/lesson-notes/$id/': typeof AuthenticatedDashboardLessonNotesIdIndexRoute
  '/dashboard/staff/$staffId/': typeof AuthenticatedDashboardStaffStaffIdIndexRoute
  '/dashboard/students/$studentId/': typeof AuthenticatedDashboardStudentsStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/redirect': typeof RedirectRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/announcements': typeof AuthenticatedDashboardAnnouncementsRoute
  '/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/dashboard/departments': typeof AuthenticatedDashboardDepartmentsRoute
  '/dashboard/exams': typeof AuthenticatedDashboardExamsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/results': typeof AuthenticatedDashboardResultsRoute
  '/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/subjects': typeof AuthenticatedDashboardSubjectsRoute
  '/dashboard/timetable': typeof AuthenticatedDashboardTimetableRoute
  '/onboarding/academic': typeof AuthenticatedOnboardingAcademicRoute
  '/onboarding/branch': typeof AuthenticatedOnboardingBranchRoute
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/attendance/staff': typeof AuthenticatedDashboardAttendanceStaffRoute
  '/dashboard/attendance/students': typeof AuthenticatedDashboardAttendanceStudentsRoute
  '/dashboard/hr/leaves': typeof AuthenticatedDashboardHrLeavesRoute
  '/dashboard/hr/payroll': typeof AuthenticatedDashboardHrPayrollRoute
  '/dashboard/staff/new': typeof AuthenticatedDashboardStaffNewRoute
  '/dashboard/students/new': typeof AuthenticatedDashboardStudentsNewRoute
  '/dashboard/lesson-notes': typeof AuthenticatedDashboardLessonNotesIndexRoute
  '/dashboard/staff': typeof AuthenticatedDashboardStaffIndexRoute
  '/dashboard/students': typeof AuthenticatedDashboardStudentsIndexRoute
  '/dashboard/lesson-notes/$id/edit': typeof AuthenticatedDashboardLessonNotesIdEditRoute
  '/dashboard/staff/$staffId/edit': typeof AuthenticatedDashboardStaffStaffIdEditRoute
  '/dashboard/students/$studentId/edit': typeof AuthenticatedDashboardStudentsStudentIdEditRoute
  '/dashboard/lesson-notes/$id': typeof AuthenticatedDashboardLessonNotesIdIndexRoute
  '/dashboard/staff/$staffId': typeof AuthenticatedDashboardStaffStaffIdIndexRoute
  '/dashboard/students/$studentId': typeof AuthenticatedDashboardStudentsStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/list': typeof ListRoute
  '/redirect': typeof RedirectRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authenticated/dashboard/announcements': typeof AuthenticatedDashboardAnnouncementsRoute
  '/_authenticated/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/_authenticated/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/_authenticated/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/_authenticated/dashboard/departments': typeof AuthenticatedDashboardDepartmentsRoute
  '/_authenticated/dashboard/exams': typeof AuthenticatedDashboardExamsRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/results': typeof AuthenticatedDashboardResultsRoute
  '/_authenticated/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/subjects': typeof AuthenticatedDashboardSubjectsRoute
  '/_authenticated/dashboard/timetable': typeof AuthenticatedDashboardTimetableRoute
  '/_authenticated/onboarding/academic': typeof AuthenticatedOnboardingAcademicRoute
  '/_authenticated/onboarding/branch': typeof AuthenticatedOnboardingBranchRoute
  '/_authenticated/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/attendance/staff': typeof AuthenticatedDashboardAttendanceStaffRoute
  '/_authenticated/dashboard/attendance/students': typeof AuthenticatedDashboardAttendanceStudentsRoute
  '/_authenticated/dashboard/hr/leaves': typeof AuthenticatedDashboardHrLeavesRoute
  '/_authenticated/dashboard/hr/payroll': typeof AuthenticatedDashboardHrPayrollRoute
  '/_authenticated/dashboard/staff/new': typeof AuthenticatedDashboardStaffNewRoute
  '/_authenticated/dashboard/students/new': typeof AuthenticatedDashboardStudentsNewRoute
  '/_authenticated/dashboard/lesson-notes/': typeof AuthenticatedDashboardLessonNotesIndexRoute
  '/_authenticated/dashboard/staff/': typeof AuthenticatedDashboardStaffIndexRoute
  '/_authenticated/dashboard/students/': typeof AuthenticatedDashboardStudentsIndexRoute
  '/_authenticated/dashboard/lesson-notes/$id/edit': typeof AuthenticatedDashboardLessonNotesIdEditRoute
  '/_authenticated/dashboard/staff/$staffId/edit': typeof AuthenticatedDashboardStaffStaffIdEditRoute
  '/_authenticated/dashboard/students/$studentId/edit': typeof AuthenticatedDashboardStudentsStudentIdEditRoute
  '/_authenticated/dashboard/lesson-notes/$id/': typeof AuthenticatedDashboardLessonNotesIdIndexRoute
  '/_authenticated/dashboard/staff/$staffId/': typeof AuthenticatedDashboardStaffStaffIdIndexRoute
  '/_authenticated/dashboard/students/$studentId/': typeof AuthenticatedDashboardStudentsStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/list'
    | '/redirect'
    | '/dashboard'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/demo/tanstack-query'
    | '/dashboard/announcements'
    | '/dashboard/assignments'
    | '/dashboard/branches'
    | '/dashboard/classes'
    | '/dashboard/departments'
    | '/dashboard/exams'
    | '/dashboard/reports'
    | '/dashboard/results'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/subjects'
    | '/dashboard/timetable'
    | '/onboarding/academic'
    | '/onboarding/branch'
    | '/onboarding/profile'
    | '/dashboard/'
    | '/dashboard/attendance/staff'
    | '/dashboard/attendance/students'
    | '/dashboard/hr/leaves'
    | '/dashboard/hr/payroll'
    | '/dashboard/staff/new'
    | '/dashboard/students/new'
    | '/dashboard/lesson-notes/'
    | '/dashboard/staff/'
    | '/dashboard/students/'
    | '/dashboard/lesson-notes/$id/edit'
    | '/dashboard/staff/$staffId/edit'
    | '/dashboard/students/$studentId/edit'
    | '/dashboard/lesson-notes/$id/'
    | '/dashboard/staff/$staffId/'
    | '/dashboard/students/$studentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/list'
    | '/redirect'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/demo/tanstack-query'
    | '/dashboard/announcements'
    | '/dashboard/assignments'
    | '/dashboard/branches'
    | '/dashboard/classes'
    | '/dashboard/departments'
    | '/dashboard/exams'
    | '/dashboard/reports'
    | '/dashboard/results'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/subjects'
    | '/dashboard/timetable'
    | '/onboarding/academic'
    | '/onboarding/branch'
    | '/onboarding/profile'
    | '/dashboard'
    | '/dashboard/attendance/staff'
    | '/dashboard/attendance/students'
    | '/dashboard/hr/leaves'
    | '/dashboard/hr/payroll'
    | '/dashboard/staff/new'
    | '/dashboard/students/new'
    | '/dashboard/lesson-notes'
    | '/dashboard/staff'
    | '/dashboard/students'
    | '/dashboard/lesson-notes/$id/edit'
    | '/dashboard/staff/$staffId/edit'
    | '/dashboard/students/$studentId/edit'
    | '/dashboard/lesson-notes/$id'
    | '/dashboard/staff/$staffId'
    | '/dashboard/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/list'
    | '/redirect'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/demo/tanstack-query'
    | '/_authenticated/dashboard/announcements'
    | '/_authenticated/dashboard/assignments'
    | '/_authenticated/dashboard/branches'
    | '/_authenticated/dashboard/classes'
    | '/_authenticated/dashboard/departments'
    | '/_authenticated/dashboard/exams'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/results'
    | '/_authenticated/dashboard/sessions'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/subjects'
    | '/_authenticated/dashboard/timetable'
    | '/_authenticated/onboarding/academic'
    | '/_authenticated/onboarding/branch'
    | '/_authenticated/onboarding/profile'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/attendance/staff'
    | '/_authenticated/dashboard/attendance/students'
    | '/_authenticated/dashboard/hr/leaves'
    | '/_authenticated/dashboard/hr/payroll'
    | '/_authenticated/dashboard/staff/new'
    | '/_authenticated/dashboard/students/new'
    | '/_authenticated/dashboard/lesson-notes/'
    | '/_authenticated/dashboard/staff/'
    | '/_authenticated/dashboard/students/'
    | '/_authenticated/dashboard/lesson-notes/$id/edit'
    | '/_authenticated/dashboard/staff/$staffId/edit'
    | '/_authenticated/dashboard/students/$studentId/edit'
    | '/_authenticated/dashboard/lesson-notes/$id/'
    | '/_authenticated/dashboard/staff/$staffId/'
    | '/_authenticated/dashboard/students/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ListRoute: typeof ListRoute
  RedirectRoute: typeof RedirectRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/onboarding/profile': {
      id: '/_authenticated/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AuthenticatedOnboardingProfileRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/branch': {
      id: '/_authenticated/onboarding/branch'
      path: '/branch'
      fullPath: '/onboarding/branch'
      preLoaderRoute: typeof AuthenticatedOnboardingBranchRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/academic': {
      id: '/_authenticated/onboarding/academic'
      path: '/academic'
      fullPath: '/onboarding/academic'
      preLoaderRoute: typeof AuthenticatedOnboardingAcademicRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/dashboard/timetable': {
      id: '/_authenticated/dashboard/timetable'
      path: '/timetable'
      fullPath: '/dashboard/timetable'
      preLoaderRoute: typeof AuthenticatedDashboardTimetableRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/subjects': {
      id: '/_authenticated/dashboard/subjects'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof AuthenticatedDashboardSubjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/sessions': {
      id: '/_authenticated/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof AuthenticatedDashboardSessionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/results': {
      id: '/_authenticated/dashboard/results'
      path: '/results'
      fullPath: '/dashboard/results'
      preLoaderRoute: typeof AuthenticatedDashboardResultsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/exams': {
      id: '/_authenticated/dashboard/exams'
      path: '/exams'
      fullPath: '/dashboard/exams'
      preLoaderRoute: typeof AuthenticatedDashboardExamsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/departments': {
      id: '/_authenticated/dashboard/departments'
      path: '/departments'
      fullPath: '/dashboard/departments'
      preLoaderRoute: typeof AuthenticatedDashboardDepartmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/classes': {
      id: '/_authenticated/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof AuthenticatedDashboardClassesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/branches': {
      id: '/_authenticated/dashboard/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof AuthenticatedDashboardBranchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/assignments': {
      id: '/_authenticated/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof AuthenticatedDashboardAssignmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/announcements': {
      id: '/_authenticated/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof AuthenticatedDashboardAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/students/': {
      id: '/_authenticated/dashboard/students/'
      path: '/students'
      fullPath: '/dashboard/students/'
      preLoaderRoute: typeof AuthenticatedDashboardStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/staff/': {
      id: '/_authenticated/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof AuthenticatedDashboardStaffIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/lesson-notes/': {
      id: '/_authenticated/dashboard/lesson-notes/'
      path: '/lesson-notes'
      fullPath: '/dashboard/lesson-notes/'
      preLoaderRoute: typeof AuthenticatedDashboardLessonNotesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/students/new': {
      id: '/_authenticated/dashboard/students/new'
      path: '/students/new'
      fullPath: '/dashboard/students/new'
      preLoaderRoute: typeof AuthenticatedDashboardStudentsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/staff/new': {
      id: '/_authenticated/dashboard/staff/new'
      path: '/staff/new'
      fullPath: '/dashboard/staff/new'
      preLoaderRoute: typeof AuthenticatedDashboardStaffNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/hr/payroll': {
      id: '/_authenticated/dashboard/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/dashboard/hr/payroll'
      preLoaderRoute: typeof AuthenticatedDashboardHrPayrollRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/hr/leaves': {
      id: '/_authenticated/dashboard/hr/leaves'
      path: '/hr/leaves'
      fullPath: '/dashboard/hr/leaves'
      preLoaderRoute: typeof AuthenticatedDashboardHrLeavesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/attendance/students': {
      id: '/_authenticated/dashboard/attendance/students'
      path: '/attendance/students'
      fullPath: '/dashboard/attendance/students'
      preLoaderRoute: typeof AuthenticatedDashboardAttendanceStudentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/attendance/staff': {
      id: '/_authenticated/dashboard/attendance/staff'
      path: '/attendance/staff'
      fullPath: '/dashboard/attendance/staff'
      preLoaderRoute: typeof AuthenticatedDashboardAttendanceStaffRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/students/$studentId/': {
      id: '/_authenticated/dashboard/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/dashboard/students/$studentId/'
      preLoaderRoute: typeof AuthenticatedDashboardStudentsStudentIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/staff/$staffId/': {
      id: '/_authenticated/dashboard/staff/$staffId/'
      path: '/staff/$staffId'
      fullPath: '/dashboard/staff/$staffId/'
      preLoaderRoute: typeof AuthenticatedDashboardStaffStaffIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/lesson-notes/$id/': {
      id: '/_authenticated/dashboard/lesson-notes/$id/'
      path: '/lesson-notes/$id'
      fullPath: '/dashboard/lesson-notes/$id/'
      preLoaderRoute: typeof AuthenticatedDashboardLessonNotesIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/students/$studentId/edit': {
      id: '/_authenticated/dashboard/students/$studentId/edit'
      path: '/students/$studentId/edit'
      fullPath: '/dashboard/students/$studentId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardStudentsStudentIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/staff/$staffId/edit': {
      id: '/_authenticated/dashboard/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/dashboard/staff/$staffId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardStaffStaffIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/lesson-notes/$id/edit': {
      id: '/_authenticated/dashboard/lesson-notes/$id/edit'
      path: '/lesson-notes/$id/edit'
      fullPath: '/dashboard/lesson-notes/$id/edit'
      preLoaderRoute: typeof AuthenticatedDashboardLessonNotesIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardAnnouncementsRoute: typeof AuthenticatedDashboardAnnouncementsRoute
  AuthenticatedDashboardAssignmentsRoute: typeof AuthenticatedDashboardAssignmentsRoute
  AuthenticatedDashboardBranchesRoute: typeof AuthenticatedDashboardBranchesRoute
  AuthenticatedDashboardClassesRoute: typeof AuthenticatedDashboardClassesRoute
  AuthenticatedDashboardDepartmentsRoute: typeof AuthenticatedDashboardDepartmentsRoute
  AuthenticatedDashboardExamsRoute: typeof AuthenticatedDashboardExamsRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardResultsRoute: typeof AuthenticatedDashboardResultsRoute
  AuthenticatedDashboardSessionsRoute: typeof AuthenticatedDashboardSessionsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSubjectsRoute: typeof AuthenticatedDashboardSubjectsRoute
  AuthenticatedDashboardTimetableRoute: typeof AuthenticatedDashboardTimetableRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAttendanceStaffRoute: typeof AuthenticatedDashboardAttendanceStaffRoute
  AuthenticatedDashboardAttendanceStudentsRoute: typeof AuthenticatedDashboardAttendanceStudentsRoute
  AuthenticatedDashboardHrLeavesRoute: typeof AuthenticatedDashboardHrLeavesRoute
  AuthenticatedDashboardHrPayrollRoute: typeof AuthenticatedDashboardHrPayrollRoute
  AuthenticatedDashboardStaffNewRoute: typeof AuthenticatedDashboardStaffNewRoute
  AuthenticatedDashboardStudentsNewRoute: typeof AuthenticatedDashboardStudentsNewRoute
  AuthenticatedDashboardLessonNotesIndexRoute: typeof AuthenticatedDashboardLessonNotesIndexRoute
  AuthenticatedDashboardStaffIndexRoute: typeof AuthenticatedDashboardStaffIndexRoute
  AuthenticatedDashboardStudentsIndexRoute: typeof AuthenticatedDashboardStudentsIndexRoute
  AuthenticatedDashboardLessonNotesIdEditRoute: typeof AuthenticatedDashboardLessonNotesIdEditRoute
  AuthenticatedDashboardStaffStaffIdEditRoute: typeof AuthenticatedDashboardStaffStaffIdEditRoute
  AuthenticatedDashboardStudentsStudentIdEditRoute: typeof AuthenticatedDashboardStudentsStudentIdEditRoute
  AuthenticatedDashboardLessonNotesIdIndexRoute: typeof AuthenticatedDashboardLessonNotesIdIndexRoute
  AuthenticatedDashboardStaffStaffIdIndexRoute: typeof AuthenticatedDashboardStaffStaffIdIndexRoute
  AuthenticatedDashboardStudentsStudentIdIndexRoute: typeof AuthenticatedDashboardStudentsStudentIdIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardAnnouncementsRoute:
      AuthenticatedDashboardAnnouncementsRoute,
    AuthenticatedDashboardAssignmentsRoute:
      AuthenticatedDashboardAssignmentsRoute,
    AuthenticatedDashboardBranchesRoute: AuthenticatedDashboardBranchesRoute,
    AuthenticatedDashboardClassesRoute: AuthenticatedDashboardClassesRoute,
    AuthenticatedDashboardDepartmentsRoute:
      AuthenticatedDashboardDepartmentsRoute,
    AuthenticatedDashboardExamsRoute: AuthenticatedDashboardExamsRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardResultsRoute: AuthenticatedDashboardResultsRoute,
    AuthenticatedDashboardSessionsRoute: AuthenticatedDashboardSessionsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSubjectsRoute: AuthenticatedDashboardSubjectsRoute,
    AuthenticatedDashboardTimetableRoute: AuthenticatedDashboardTimetableRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAttendanceStaffRoute:
      AuthenticatedDashboardAttendanceStaffRoute,
    AuthenticatedDashboardAttendanceStudentsRoute:
      AuthenticatedDashboardAttendanceStudentsRoute,
    AuthenticatedDashboardHrLeavesRoute: AuthenticatedDashboardHrLeavesRoute,
    AuthenticatedDashboardHrPayrollRoute: AuthenticatedDashboardHrPayrollRoute,
    AuthenticatedDashboardStaffNewRoute: AuthenticatedDashboardStaffNewRoute,
    AuthenticatedDashboardStudentsNewRoute:
      AuthenticatedDashboardStudentsNewRoute,
    AuthenticatedDashboardLessonNotesIndexRoute:
      AuthenticatedDashboardLessonNotesIndexRoute,
    AuthenticatedDashboardStaffIndexRoute:
      AuthenticatedDashboardStaffIndexRoute,
    AuthenticatedDashboardStudentsIndexRoute:
      AuthenticatedDashboardStudentsIndexRoute,
    AuthenticatedDashboardLessonNotesIdEditRoute:
      AuthenticatedDashboardLessonNotesIdEditRoute,
    AuthenticatedDashboardStaffStaffIdEditRoute:
      AuthenticatedDashboardStaffStaffIdEditRoute,
    AuthenticatedDashboardStudentsStudentIdEditRoute:
      AuthenticatedDashboardStudentsStudentIdEditRoute,
    AuthenticatedDashboardLessonNotesIdIndexRoute:
      AuthenticatedDashboardLessonNotesIdIndexRoute,
    AuthenticatedDashboardStaffStaffIdIndexRoute:
      AuthenticatedDashboardStaffStaffIdIndexRoute,
    AuthenticatedDashboardStudentsStudentIdIndexRoute:
      AuthenticatedDashboardStudentsStudentIdIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedOnboardingRouteRouteChildren {
  AuthenticatedOnboardingAcademicRoute: typeof AuthenticatedOnboardingAcademicRoute
  AuthenticatedOnboardingBranchRoute: typeof AuthenticatedOnboardingBranchRoute
  AuthenticatedOnboardingProfileRoute: typeof AuthenticatedOnboardingProfileRoute
}

const AuthenticatedOnboardingRouteRouteChildren: AuthenticatedOnboardingRouteRouteChildren =
  {
    AuthenticatedOnboardingAcademicRoute: AuthenticatedOnboardingAcademicRoute,
    AuthenticatedOnboardingBranchRoute: AuthenticatedOnboardingBranchRoute,
    AuthenticatedOnboardingProfileRoute: AuthenticatedOnboardingProfileRoute,
  }

const AuthenticatedOnboardingRouteRouteWithChildren =
  AuthenticatedOnboardingRouteRoute._addFileChildren(
    AuthenticatedOnboardingRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedOnboardingRouteRoute: typeof AuthenticatedOnboardingRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedOnboardingRouteRoute:
    AuthenticatedOnboardingRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ListRoute: ListRoute,
  RedirectRoute: RedirectRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
